[workspace.package]
version = "0.2.0-alpha"
edition = "2021"
rust-version = "1.82"
authors = ["OpenVM Authors"]
homepage = "https://openvm.dev"
repository = "https://github.com/openvm-org/"
license = "MIT"

[workspace]
members = [
    "benchmarks",
    "crates/prof",
    "crates/sdk",
    "crates/cli",
    "crates/circuits/mod-builder",
    "crates/circuits/poseidon2-air",
    "crates/circuits/primitives",
    "crates/circuits/primitives/derive",
    "crates/toolchain/transpiler",
    "crates/toolchain/openvm",
    "crates/toolchain/build",
    "crates/toolchain/instructions",
    "crates/toolchain/instructions/derive",
    "crates/toolchain/macros",
    "crates/toolchain/platform",
    "crates/toolchain/tests",
    "crates/vm",
    "extensions/rv32im/circuit",
    "extensions/rv32im/transpiler",
    "extensions/rv32im/guest",
    "extensions/rv32im/tests",
    "extensions/rv32-adapters",
    "extensions/native/circuit",
    "extensions/native/compiler",
    "extensions/native/compiler/derive",
    "extensions/native/recursion",
    "extensions/native/transpiler",
    "extensions/native/guest-macro",
    "extensions/native/tests",
    "extensions/algebra/circuit",
    "extensions/algebra/transpiler",
    "extensions/algebra/guest",
    "extensions/algebra/moduli-setup",
    "extensions/algebra/tests",
    "extensions/bigint/circuit",
    "extensions/bigint/transpiler",
    "extensions/bigint/guest",
    "extensions/bigint/tests",
    "extensions/keccak256/circuit",
    "extensions/keccak256/transpiler",
    "extensions/keccak256/guest",
    "extensions/keccak256/tests",
    "extensions/sha256/circuit",
    "extensions/sha256/transpiler",
    "extensions/sha256/guest",
    "extensions/sha256/tests",
    "extensions/ecc/circuit",
    "extensions/ecc/transpiler",
    "extensions/ecc/guest",
    "extensions/ecc/sw-setup",
    "extensions/ecc/tests",
    "extensions/pairing/circuit",
    "extensions/pairing/transpiler",
    "extensions/pairing/guest",
    "extensions/pairing/tests",
    "extensions/snark-verifier",
]
exclude = ["crates/sdk/example"]
resolver = "2"

# Fastest runtime configuration
[profile.release]
opt-level = 3
lto = "thin"
debug = "line-tables-only"
strip = true
panic = "unwind"
codegen-units = 16

[profile.profiling]
inherits = "release"
debug = 2
strip = false

# Make sure debug symbols are in the bench profile for flamegraphs
[profile.bench]
inherits = "profiling"

# This will compile slowly
[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

[profile.dev]
opt-level = 1

# For O1 optimization but still fast(ish) compile times
[profile.fast]
inherits = "dev"
debug-assertions = true
# better recompile times
incremental = true
lto = "thin"

[workspace.dependencies]
# Stark Backend
openvm-stark-backend = { git = "https://github.com/openvm-org/stark-backend.git", rev = "47a0bda", default-features = false }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", rev = "47a0bda", default-features = false }

# OpenVM
openvm-sdk = { path = "crates/sdk", default-features = false }
cargo-openvm = { path = "crates/cli", default-features = false }
openvm-mod-circuit-builder = { path = "crates/circuits/mod-builder", default-features = false }
openvm-poseidon2-air = { path = "crates/circuits/poseidon2-air", default-features = false }
openvm-sha256-air = { path = "crates/circuits/sha256-air", default-features = false }
openvm-circuit-primitives = { path = "crates/circuits/primitives", default-features = false }
openvm-circuit-primitives-derive = { path = "crates/circuits/primitives/derive", default-features = false }
openvm = { path = "crates/toolchain/openvm", default-features = false }
openvm-build = { path = "crates/toolchain/build", default-features = false }
openvm-instructions = { path = "crates/toolchain/instructions", default-features = false }
openvm-instructions-derive = { path = "crates/toolchain/instructions/derive", default-features = false }
openvm-macros-common = { path = "crates/toolchain/macros", default-features = false }
openvm-platform = { path = "crates/toolchain/platform", default-features = false }
openvm-transpiler = { path = "crates/toolchain/transpiler", default-features = false }
openvm-circuit = { path = "crates/vm", default-features = false }
openvm-circuit-derive = { path = "crates/vm/derive", default-features = false }
openvm-toolchain-tests = { path = "crates/toolchain/tests", default-features = false }
openvm-custom-insn = { path = "crates/toolchain/custom_insn", default-features = false }

# Extensions
openvm-rv32im-circuit = { path = "extensions/rv32im/circuit", default-features = false }
openvm-rv32im-transpiler = { path = "extensions/rv32im/transpiler", default-features = false }
openvm-rv32im-guest = { path = "extensions/rv32im/guest", default-features = false }
openvm-rv32-adapters = { path = "extensions/rv32-adapters", default-features = false }
openvm-native-circuit = { path = "extensions/native/circuit", default-features = false }
openvm-native-compiler = { path = "extensions/native/compiler", default-features = false }
openvm-native-compiler-derive = { path = "extensions/native/compiler/derive", default-features = false }
openvm-native-recursion = { path = "extensions/native/recursion", default-features = false }
openvm-native-guest-macro = { path = "extensions/native/guest-macro", default-features = false }
openvm-native-integration-test = { path = "extensions/native/guest-macro/test", default-features = false }
openvm-native-transpiler = { path = "extensions/native/transpiler", default-features = false }
openvm-keccak256-circuit = { path = "extensions/keccak256/circuit", default-features = false }
openvm-keccak256-transpiler = { path = "extensions/keccak256/transpiler", default-features = false }
openvm-keccak256-guest = { path = "extensions/keccak256/guest", default-features = false }
openvm-sha256-circuit = { path = "extensions/sha256/circuit", default-features = false }
openvm-sha256-transpiler = { path = "extensions/sha256/transpiler", default-features = false }
openvm-sha256-guest = { path = "extensions/sha256/guest", default-features = false }
openvm-bigint-circuit = { path = "extensions/bigint/circuit", default-features = false }
openvm-bigint-transpiler = { path = "extensions/bigint/transpiler", default-features = false }
openvm-bigint-guest = { path = "extensions/bigint/guest", default-features = false }
openvm-algebra-circuit = { path = "extensions/algebra/circuit", default-features = false }
openvm-algebra-transpiler = { path = "extensions/algebra/transpiler", default-features = false }
openvm-algebra-guest = { path = "extensions/algebra/guest", default-features = false }
openvm-algebra-moduli-setup = { path = "extensions/algebra/moduli-setup", default-features = false }
openvm-algebra-complex-macros = { path = "extensions/algebra/guest/src/field/complex-macros", default-features = false }
openvm-ecc-circuit = { path = "extensions/ecc/circuit", default-features = false }
openvm-ecc-transpiler = { path = "extensions/ecc/transpiler", default-features = false }
openvm-ecc-guest = { path = "extensions/ecc/guest", default-features = false }
openvm-ecc-sw-setup = { path = "extensions/ecc/sw-setup", default-features = false }
openvm-pairing-circuit = { path = "extensions/pairing/circuit", default-features = false }
openvm-pairing-transpiler = { path = "extensions/pairing/transpiler", default-features = false }
openvm-pairing-guest = { path = "extensions/pairing/guest", default-features = false }
openvm-snark-verifier = { path = "extensions/snark-verifier", default-features = false }

# Plonky3
p3-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-baby-bear = { git = "https://github.com/Plonky3/Plonky3.git", features = [
    "nightly-features",
], rev = "b0591e9" }
p3-util = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-challenger = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-dft = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-fri = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-keccak = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-keccak-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-blake3 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-mds = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-merkle-tree = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-monty-31 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-poseidon = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-poseidon2-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-uni-stark = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-maybe-rayon = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" } # the "parallel" feature is NOT on by default to allow single-threaded benchmarking
p3-bn254-fr = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }

snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier", branch = "zkvm-v0.1", default-features = false, features = [
    "loader_halo2",
    "halo2-axiom",
    "display",
] }
zkhash = { git = "https://github.com/HorizenLabs/poseidon2.git", rev = "bb476b9" }
halo2curves-axiom = "0.5.3"

rayon = "1.10"
tracing = "0.1.40"
bon = "3.2.0"
serde_json = "1.0.117"
serde_with = "3.11.0"
clap = "4.5.23"
toml = "0.8.14"
lazy_static = "1.5.0"
once_cell = "1.19.0"
derive-new = "0.6.0"
derive_more = "1.0.0"
derivative = "2.2.0"
strum_macros = "0.26.4"
strum = { version = "0.26.3", features = ["derive"] }
enum-utils = "0.1.1"
backtrace = "0.3.71"
metrics = "0.23.0"
metrics-derive = "0.1.0"
cfg-if = "1.0.0"
inferno = "0.11.21"
test-case = "3.3.1"
test-log = "0.2.16"
enum_dispatch = "0.3.13"
eyre = "0.6.12"
tempfile = "3.13.0"
thiserror = "1.0.65"
rustc-hash = "2.0.0"
static_assertions = "1.1.0"
async-trait = "0.1.83"
getset = "0.1.3"
rrs-lib = "0.1.0"
rand = { version = "0.8.5", default-features = false }
hex = { version = "0.4.3", default-features = false }
serde-big-array = "0.5.1"

# default-features = false for no_std for use in guest programs
itertools = { version = "0.13.0", default-features = false }
bincode = { version = "2.0.0-rc.3", default-features = false }
bitcode = { version = "0.6.3", default-features = false, features = ["serde"] }
serde = { version = "1.0.201", default-features = false, features = ["derive"] }
hex-literal = { version = "0.4.1", default-features = false }
bytemuck = { version = "1.20.0", default-features = false }

# cryptography, default-features = false for no_std
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
k256 = { version = "0.13.3", default-features = false }
elliptic-curve = { version = "0.13.8", default-features = false }
ecdsa = { version = "0.16.9", default-features = false }
num-bigint = { version = "0.4.6", default-features = false }
num-integer = { version = "0.1.46", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
ff = { version = "0.13.0", default-features = false }

# For local development. Add to your `.cargo/config.toml`
# [patch."https://github.com/Plonky3/Plonky3.git"]
# p3-air = { path = "../Plonky3/air" }
# p3-field = { path = "../Plonky3/field" }
# p3-commit = { path = "../Plonky3/commit" }
# p3-matrix = { path = "../Plonky3/matrix" }
# p3-baby-bear = { path = "../Plonky3/baby-bear" }
# p3-util = { path = "../Plonky3/util" }
# p3-challenger = { path = "../Plonky3/challenger" }
# p3-dft = { path = "../Plonky3/dft" }
# p3-fri = { path = "../Plonky3/fri" }
# p3-goldilocks = { path = "../Plonky3/goldilocks" }
# p3-keccak = { path = "../Plonky3/keccak" }
# p3-keccak-air = { path = "../Plonky3/keccak-air" }
# p3-blake3 = { path = "../Plonky3/blake3" }
# p3-mds = { path = "../Plonky3/mds" }
# p3-merkle-tree = { path = "../Plonky3/merkle-tree" }
# p3-poseidon2 = { path = "../Plonky3/poseidon2" }
# p3-symmetric = { path = "../Plonky3/symmetric" }
# p3-uni-stark = { path = "../Plonky3/uni-stark" }
# p3-maybe-rayon = { path = "../Plonky3/maybe-rayon" }
# p3-bn254-fr = { path = "../Plonky3/bn254-fr" }
