[package]
name = "openvm-transpiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-stark-backend.workspace = true
openvm-platform.workspace = true
openvm-instructions.workspace = true

strum.workspace = true
eyre.workspace = true
thiserror.workspace = true
elf = "0.7.4"
rrs-lib.workspace = true
tracing.workspace = true
derive_more = { workspace = true, features = ["from"] }

[dev-dependencies]
test-case.workspace = true
openvm-circuit = { workspace = true, features = ["test-utils"] }
openvm-build.workspace = true
openvm-stark-sdk.workspace = true
tempfile.workspace = true
serde = { workspace = true, features = ["alloc"] }
openvm-algebra-transpiler = { workspace = true }
openvm-rv32im-transpiler = { workspace = true }

[features]
parallel = ["openvm-circuit/parallel"]
function-span = ["openvm-circuit/function-span"]
