[package]
name = "openvm-benchmarks"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
openvm-build.workspace = true
openvm-circuit.workspace = true
openvm-circuit-primitives-derive.workspace = true
openvm-sdk.workspace = true
openvm-stark-backend.workspace = true
openvm-stark-sdk.workspace = true
openvm-transpiler.workspace = true
openvm-algebra-circuit.workspace = true
openvm-algebra-transpiler.workspace = true
openvm-ecc-circuit.workspace = true
openvm-ecc-transpiler.workspace = true
openvm-keccak256-circuit.workspace = true
openvm-keccak256-transpiler.workspace = true
openvm-keccak256-guest.workspace = true
openvm-native-circuit.workspace = true
openvm-native-compiler.workspace = true
openvm-native-recursion = { workspace = true, features = ["test-utils"] }
openvm-rv32im-circuit.workspace = true
openvm-rv32im-transpiler.workspace = true

clap = { version = "4.5.9", features = ["derive", "env"] }
eyre.workspace = true
tempfile.workspace = true
metrics.workspace = true
tracing.workspace = true
hex.workspace = true
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
rand_chacha = { version = "0.3", default-features = false }
k256 = { workspace = true, features = ["ecdsa"] }
tiny-keccak.workspace = true
derive-new.workspace = true
derive_more = { workspace = true, features = ["from"] }
num-bigint = { workspace = true, features = ["std", "serde"] }
serde.workspace = true
bincode = { version = "2.0.0-rc.3" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pprof = { version = "0.13", features = [
    "criterion",
    "flamegraph",
    "frame-pointer",
] }

[features]
default = ["parallel", "mimalloc", "bench-metrics"]
bench-metrics = [
    "openvm-native-recursion/bench-metrics",
    "openvm-native-compiler/bench-metrics",
]
profiling = ["openvm-sdk/profiling"]
aggregation = []
static-verifier = ["openvm-native-recursion/static-verifier"]
parallel = ["openvm-native-recursion/parallel"]
mimalloc = ["openvm-circuit/mimalloc"]
jemalloc = ["openvm-circuit/jemalloc"]
jemalloc-prof = ["openvm-circuit/jemalloc-prof"]
nightly-features = ["openvm-circuit/nightly-features"]

[[bench]]
name = "fibonacci_execute"
harness = false

[[bench]]
name = "regex_execute"
harness = false

[[bin]]
name = "fib_e2e"
