[package]
name = "openvm-bigint-guest"
description = "OpenVM guest library for bigint"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm = { workspace = true }
openvm-platform = { workspace = true }
strum_macros = { workspace = true }

serde = { workspace = true, features = ["alloc"] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
num-bigint.workspace = true
num-traits.workspace = true

[features]
default = []
std = ["serde/std"]
export-intrinsics = [] # export extern no_mangle functions for external linkage
